### ISSUE TITLE
jwt command is not triggered

### ISSUE THREAD

**Issue by truongvinht** [cage1016/alfred-devtoys#24]
Hello, thanks for building great tool for alfred. Unfortunately the feature 'jwt' seems not to work as expected.

After I typed 'jwt ey..........' nothing happens, except I get the suggestion to use the search engine instead. Did I make any mistake?

kind regards
Truong Vinh

**Comment by cage1016** [comment]
Hi, @truongvinht 

![CleanShot 2024-06-28 at 22 53 58@2x](https://github.com/cage1016/alfred-devtoys/assets/678607/2cbbc18a-89de-4b2f-9b98-32167970a463)

![CleanShot 2024-06-28 at 22 55 12@2x](https://github.com/cage1016/alfred-devtoys/assets/678607/32869109-d7a3-4475-8835-77babc2621c3)

JWT Decode is a Universal Action. Please use action selected item to enable JWT decode
