### ISSUE TITLE
clipboard: cannot use when CGO_ENABLED=0

### ISSUE THREAD

**Issue by bmorgenthaler** [cage1016/alfred-devtoys#5]
Running on macOS 12.6.1 Macbook Pro M1 and when trying to encode a string I get this alert and no encoded string.

I also had numerous System Security alerts about `exe` that I had to navigate around.

**Comment by cage1016** [comment]
![image](https://user-images.githubusercontent.com/678607/197989338-76bc3787-1d8e-4321-9e14-9c3cdcb3bae4.png)

first, for security issue. Please check system/Security & Privacy allow `App store and identified developers`

![CleanShot 2022-10-26 at 17 28 41@2x](https://user-images.githubusercontent.com/678607/197990235-8d197f3b-dd89-42c9-99d8-970b6ec68445.jpg)

second, cause i don't have arm64 Mac, Cloud you provide more information

**Comment by LampPrinter** [comment]
Same issue on M1 MacBook. Surprisingly this started when I updated to Ventura. On MacOS Monterey it was fine.

**Comment by cage1016** [comment]
```go
	query := args[0]
	if strings.TrimSpace(query) == "" {
		query = string(clipboard.Read(clipboard.FmtText))  👈️👈️👈️
	}
	log.Println(query)
```

In v1.5, whatever `encode` or `qrcode` command, every command will use latest clipboard value if input is empty by default. The root cause is due to `https://github.com/golang-design/clipboard` error

@bmorgenthaler @LampPrinter Cloud both of you provide your Mac system info (OS, Processor etc.). I will deep dive to check if any issue at M1 for use this third-party package

**Comment by LampPrinter** [comment]
Apple M1 MacBook Air
MacOS Ventura 13.0 (22A380)

Gatekeeper disabled.
Anything else?

<img width="628" alt="iShot_2022-10-27_11 17 21" src="https://user-images.githubusercontent.com/7559328/198201900-4f42e357-8569-4d45-97d8-50ffd41930e2.png">

<img width="628" alt="iShot_2022-10-27_11 17 36" src="https://user-images.githubusercontent.com/7559328/198201917-67ddecf2-a15a-4ca3-98c7-00afb16b08b5.png">

**Comment by bmorgenthaler** [comment]
MacBookPro18,1
M1 MacBook Pro (16-inch, 2021)
16GB
macOS Monterey 12.6.1

SIP / Gatekeeper enabled

**Comment by bmorgenthaler** [comment]
> 

Same issue as @LampPrinter

`[11:30:55.815] ERROR: DevToys[Script Filter] JSON error: JSON text did not start with array or object and option to allow fragments not set. around line 1, column 0. in JSON:
CAB6A31E-1AA3-4BDC-9C4B-6B43ADA97100`

**Comment by cage1016** [comment]
Where do both of you execute `./exe`? Download `exe.zip` and unzip.  This one is individual execution binary for reading clipboard testing. 

copy any text before execute binary

```sh
$ ./exe 
# should output latest clipboard text
```

**Comment by LampPrinter** [comment]
> Where do both of you execute `./exe`? Download `exe.zip` and unzip. This one is individual execution binary for reading clipboard testing.
> 
> copy any text before execute binary
> 
> ```shell
> $ ./exe 
> # should output latest clipboard text
> ```

Oh.
Yeah, its working fine in terminal. ✅

Earlier, I replaced the "exe" file in workflow with the new one.

**Comment by cage1016** [comment]
@LampPrinter Thanks for your feedback. I will deliver revised version workflow to give you a try. If everything works as expected and i will adopt this solution and push a new release to fix clipboard issue at Apple M1.

**Comment by cage1016** [comment]
@bmorgenthaler @LampPrinter 

[Release v1.5.1 Pre release · cage1016/alfred-devtoys](https://github.com/cage1016/alfred-devtoys/releases/tag/v1.5.1-rc.1)

Please have a try pre release version and make sure everything work as expected. Thanks.

**Comment by LampPrinter** [comment]
@cage1016 
Working fine now.

Some typos to be fixed.

<img width="310" alt="iShot_2022-11-03_09 40 06" src="https://user-images.githubusercontent.com/7559328/199646367-a7a2fd83-2d81-4c27-8394-b90ae8aa3321.png">

<img width="628" alt="iShot_2022-11-03_09 40 36" src="https://user-images.githubusercontent.com/7559328/199646381-3bd25158-8ba4-4649-b117-5d4900dd573d.png">
