### ISSUE TITLE
Distributed exe cannot be verifed by macOS

### ISSUE THREAD

**Issue by bmorgenthaler** [cage1016/alfred-devtoys#7]
Just updated to the latest version to test the clipboard issues on the M1 and received the "exe" cannot be opened message.
![image](https://user-images.githubusercontent.com/840560/199722779-bc4a2c8c-440d-4011-a9ab-1eb34113846c.png)

I do have "App Store and Identified developers" selected  in Security & Privacy preferences.
![image](https://user-images.githubusercontent.com/840560/199722982-1383ab92-c23a-4d0a-853b-219d0103c2da.png)

So clicking on Allow Anyway let's me try the workflow again with another warning about exe not being verified.
![image](https://user-images.githubusercontent.com/840560/199723144-719107b1-7359-4e1b-b3d6-5c6c39ffb3fb.png)

**Comment by cage1016** [comment]
For now. the only one solution is follow the alert message to click `Open` button.

same situation as [Fixing the oc and Red Hat OpenShift install "not downloaded" error on macOS | Red Hat Developer](https://developers.redhat.com/blog/2019/11/20/fixing-the-oc-and-red-hat-openshift-install-not-downloaded-error-on-macos#)

**Comment by cage1016** [comment]
@bmorgenthaler Please have a try [Release v1.7.0 RC 1 Pre release](https://github.com/cage1016/alfred-devtoys/releases/tag/v1.7.0-rc.1) with code sign and notarize support.

It's very appreciated that you could feedback if v1.7.0 pre release solved security issue or not.

**Comment by cage1016** [comment]
[Release 1.7.0 · cage1016/alfred-devtoys](https://github.com/cage1016/alfred-devtoys/releases/tag/v1.7.0)
