### ISSUE TITLE
Request: Add data-uri encoding

### ISSUE THREAD

**Issue by contentfree** [cage1016/alfred-devtoys#8]
It looks like DevToys is going to replace a lot of my current Alfred workflows. One tool that would be useful is encoding in data URI scheme (see "Data URI scheme" workflow by Igor Rzegocki for an example).

**Comment by cage1016** [comment]
![CleanShot 2022-11-06 at 23 49 51@2x](https://user-images.githubusercontent.com/678607/200180646-8ac42198-445e-4eab-a9fb-a76dfef40fd1.jpg)

[cage1016/alfred-devtoys: A Swiss Army knife for developers for Alfred](https://github.com/cage1016/alfred-devtoys#image-base64-encoder)

**Comment by cage1016** [comment]
Please have a look. If this function fit your request and i will close this issue.
